name: .NET Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Test (headless)
        env:
          HEADLESS: "1"
        run: dotnet test SteamBookstoreTests/SteamBookstoreTests.csproj --settings SteamBookstoreTests/test.runsettings --logger "trx;LogFileName=testResults.trx"
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: SteamBookstoreTests/allure-results
